//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastroWinForms.Conexao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public int PessoaId { get; set; }
        public string CPFCNPJ { get; set; }
        public string Nome { get; set; }
        public System.DateTime Data_Nascimento { get; set; }
        public string Sobrenome { get; set; }
        public string Cep { get; set; }
        public string Logradouro { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public string TipoPessoa { get; set; }
    }
}
